# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/ADC_FMC_const.xdc

# Block Designs: bd/top/top.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top || ORIG_REF_NAME==top} -quiet] -quiet

# IP: bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_processing_system7_0_0 || ORIG_REF_NAME==top_processing_system7_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_quad_spi_0_0/top_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_quad_spi_0_0 || ORIG_REF_NAME==top_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/top/ip/top_ps7_0_axi_periph_0/top_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_ps7_0_axi_periph_0 || ORIG_REF_NAME==top_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/top/ip/top_rst_ps7_0_100M_0/top_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_rst_ps7_0_100M_0 || ORIG_REF_NAME==top_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/top/ip/top_xbar_0/top_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_xbar_0 || ORIG_REF_NAME==top_xbar_0} -quiet] -quiet

# IP: bd/top/ip/top_selectio_wiz_0_0/top_selectio_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_selectio_wiz_0_0 || ORIG_REF_NAME==top_selectio_wiz_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_gpio_0_0/top_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_gpio_0_0 || ORIG_REF_NAME==top_axi_gpio_0_0} -quiet] -quiet

# IP: bd/top/ip/top_axi_gpio_1_0/top_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_axi_gpio_1_0 || ORIG_REF_NAME==top_axi_gpio_1_0} -quiet] -quiet

# IP: bd/top/ip/top_word_inverter_0_0/top_word_inverter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_word_inverter_0_0 || ORIG_REF_NAME==top_word_inverter_0_0} -quiet] -quiet

# IP: bd/top/ip/top_auto_pc_0/top_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_auto_pc_0 || ORIG_REF_NAME==top_auto_pc_0} -quiet] -quiet

# XDC: /home/dyerbm/Documents/Mac-PhD/Verilog-Tests/SPI_Tests/SPI_Tests.gen/sources_1/bd/top/top_ooc.xdc
