# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/soup/Documents/ESpecFirmware/Verilog/SPI_Tests/SPI_Tests.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
# IP: The module: 'top_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/soup/Documents/ESpecFirmware/Verilog/SPI_Tests/SPI_Tests.gen/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/soup/Documents/ESpecFirmware/Verilog/SPI_Tests/SPI_Tests.srcs/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xci
# IP: The module: 'top_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/soup/Documents/ESpecFirmware/Verilog/SPI_Tests/SPI_Tests.gen/sources_1/bd/top/ip/top_processing_system7_0_0/top_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
