#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Dec 14 10:15:41 EST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim bench2_behav -key {Behavioral:sim_1:Functional:bench2} -tclbatch bench2.tcl -log simulate.log"
xsim bench2_behav -key {Behavioral:sim_1:Functional:bench2} -tclbatch bench2.tcl -log simulate.log

